#!/bin/bash

# Generate comprehensive lock mode key bindings
# This script creates bindings for all common keys that users might press
# while in lock mode, ensuring they all forward to the application.

# Keys are bound in categories to ensure complete coverage:
# 1. All printable ASCII characters (space through ~)
# 2. All Ctrl+letter combinations (C-a through C-z)  
# 3. All Alt+letter combinations (M-a through M-z)
# 4. Number row (0-9)
# 5. Function keys (F1-F24 and their modifiers)
# 6. Special/navigation keys with modifiers
# 7. Symbols and punctuation

# Output can be sourced directly into tmux config
# Usage: tmux source-file <(bash generate-lock-mode-bindings.sh)

set -e

# Arrays to hold all key definitions
declare -a ALL_KEYS

# 0. Plain letters (a-z and A-Z) - CRITICAL for normal typing!
for i in {97..122}; do
    char=$(printf \\$(printf '%03o' $i))
    ALL_KEYS+=("$char")
done
for i in {65..90}; do
    char=$(printf \\$(printf '%03o' $i))
    ALL_KEYS+=("$char")
done

# 1. Control keys (C-a through C-z) - 26 keys
for i in {97..122}; do
    char=$(printf \\$(printf '%03o' $i))
    ALL_KEYS+=("C-$char")
done

# 2. Alt/Meta keys (M-a through M-z) - 26 keys
for i in {97..122}; do
    char=$(printf \\$(printf '%03o' $i))
    ALL_KEYS+=("M-$char")
done

# 3. Alt/Meta with Shift (M-A through M-Z) - 26 keys
for i in {65..90}; do
    char=$(printf \\$(printf '%03o' $i))
    ALL_KEYS+=("M-$char")
done

# 4. Numbers 0-9
for num in {0..9}; do
    ALL_KEYS+=("$num")
done

# 5. Alt+Number combinations
for num in {0..9}; do
    ALL_KEYS+=("M-$num")
done

# 6. Function keys F1-F12 (most terminals support these)
# F13-F20 are not universally supported and cause "unknown key" warnings on startup
for fn in {1..12}; do
    ALL_KEYS+=("F$fn")
    ALL_KEYS+=("S-F$fn")      # Shift+Fn
    ALL_KEYS+=("C-F$fn")      # Ctrl+Fn
    ALL_KEYS+=("M-F$fn")      # Alt+Fn
done

# 7. Arrow keys with modifiers
ARROWS=("Up" "Down" "Left" "Right")
for arrow in "${ARROWS[@]}"; do
    ALL_KEYS+=("$arrow")
    ALL_KEYS+=("S-$arrow")    # Shift+Arrow
    ALL_KEYS+=("C-$arrow")    # Ctrl+Arrow
    ALL_KEYS+=("M-$arrow")    # Alt+Arrow
done

# 8. Special/Navigation keys
SPECIAL=("Home" "End" "PageUp" "PageDown" "Insert" "Delete" "NPage" "PPage")
for key in "${SPECIAL[@]}"; do
    ALL_KEYS+=("$key")
    ALL_KEYS+=("S-$key")
    ALL_KEYS+=("C-$key")
    ALL_KEYS+=("M-$key")
done

# 9. Punctuation and symbols  
SYMBOLS=("!" "@" "#" "\$" "%" "^" "&" "*" "(" ")" "-" "=" "[" "]" "{" "}" ";" ":" "'" "\"" "," "." "?" "/" "|" " " "Tab" "Enter" "BSpace" "Escape")
for sym in "${SYMBOLS[@]}"; do
    ALL_KEYS+=("$sym")
done

# Remove duplicates while preserving order
declare -a UNIQUE_KEYS
declare -A SEEN

for key in "${ALL_KEYS[@]}"; do
    if [[ -z "${SEEN[$key]}" ]]; then
        UNIQUE_KEYS+=("$key")
        SEEN[$key]=1
    fi
done

# Output the bindings
echo "# Lock Mode - Comprehensive Key Bindings"
echo "# Auto-generated by generate-lock-mode-bindings.sh"
echo "# This file contains bindings for ${#UNIQUE_KEYS[@]} keys"
echo ""

for key in "${UNIQUE_KEYS[@]}"; do
    # Skip keys that might cause issues
    case "$key" in
        # Skip Ctrl+g as it's already defined separately
        "C-g") continue ;;
        # Skip keys that are problematic in some terminals
        "C-d") continue ;;  # EOF
        "C-z") continue ;;  # Suspend
    esac
    
    # Handle special quoting for single and double quotes
    if [ "$key" = "'" ]; then
        # Single quote: use double quotes to wrap
        echo "bind -T locked \"'\" send-keys \"'\" \\; switch-client -T locked"
    elif [ "$key" = '"' ]; then
        # Double quote: use single quotes to wrap
        echo "bind -T locked '\"' send-keys '\"' \\; switch-client -T locked"
    else
        # All other keys: use single quotes
        echo "bind -T locked '$key' send-keys '$key' \\; switch-client -T locked"
    fi
done

echo ""
echo "# End of comprehensive lock mode bindings"
